/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CloserRouteImport } from './routes/closer'
import { Route as HkRouteImport } from './routes/hk'
import { Route as LabRouteImport } from './routes/lab'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as IssuerIdRouteImport } from './routes/issuer.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CloserRoute = CloserRouteImport.update({
  id: '/closer',
  path: '/closer',
  getParentRoute: () => rootRouteImport,
} as any)
const HkRoute = HkRouteImport.update({
  id: '/hk',
  path: '/hk',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuerIdRoute = IssuerIdRouteImport.update({
  id: '/issuer/$id',
  path: '/issuer/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/closer': typeof CloserRoute
  '/hk': typeof HkRoute
  '/lab': typeof LabRoute
  '/rules': typeof RulesRoute
  '/issuer/$id': typeof IssuerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/closer': typeof CloserRoute
  '/hk': typeof HkRoute
  '/lab': typeof LabRoute
  '/rules': typeof RulesRoute
  '/issuer/$id': typeof IssuerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/closer': typeof CloserRoute
  '/hk': typeof HkRoute
  '/lab': typeof LabRoute
  '/rules': typeof RulesRoute
  '/issuer/$id': typeof IssuerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/closer' | '/hk' | '/lab' | '/rules' | '/issuer/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/closer' | '/hk' | '/lab' | '/rules' | '/issuer/$id'
  id: '__root__' | '/' | '/closer' | '/hk' | '/lab' | '/rules' | '/issuer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CloserRoute: typeof CloserRoute
  HkRoute: typeof HkRoute
  LabRoute: typeof LabRoute
  RulesRoute: typeof RulesRoute
  IssuerIdRoute: typeof IssuerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closer': {
      id: '/closer'
      path: '/closer'
      fullPath: '/closer'
      preLoaderRoute: typeof CloserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hk': {
      id: '/hk'
      path: '/hk'
      fullPath: '/hk'
      preLoaderRoute: typeof HkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuer/$id': {
      id: '/issuer/$id'
      path: '/issuer/$id'
      fullPath: '/issuer/$id'
      preLoaderRoute: typeof IssuerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CloserRoute: CloserRoute,
  HkRoute: HkRoute,
  LabRoute: LabRoute,
  RulesRoute: RulesRoute,
  IssuerIdRoute: IssuerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
